---
hero_image: images/banner.png
title: Project Vitrine
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Maak een vitrine van je webprojecten.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - title: Inleiding
  - title: Links toevoegen aan webpagina's
  - title: 'Uitdaging: voeg nog een link toe'
  - title: Link naar een Trinket
  - title: 'Uitdaging: maak een lijst van je projecten'
  - title: Projecten insluiten
  - title: 'Uitdaging: meer projecten insluiten'
  - title: Maak een inhoudsopgave
  - title: Terug naar boven
  - title: 'Uitdaging: verbeter je vitrine'
  - title: 'Uitdaging: maak een nieuwe vitrine'
