---
hero_image: images/banner.png
title: Showcase ng Proyekto
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disenyo-1, programming-0, phys-comp-0, paggawa-0, pamayanan-0
description: Lumikha ng isang showcase ng iyong mga proyekto sa web.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Panimula
  - 
    title: Pagdaragdag ng mga Link sa Mga Webpage
  - 
    title: 'Hamon: Magdagdag ng isa pang link'
  - 
    title: Mag-link sa Isang Trinket
    completion:
      - engaged
  - 
    title: 'Hamon: Lumikha ng Listahan Para sa iyong mga Proyekto'
  - 
    title: Pag-embed ng mga Proyekto
  - 
    title: 'Hamon: Mag-embed ng Marami pang Proyekto'
  - 
    title: Lumikha ng isang Talahanayan ng mga Nilalaman
  - 
    title: Pagbabalik sa pinakasimula
    completion:
      - internal
  - 
    title: 'Hamon: Pagbutihin ang Iyong Showcase'
  - 
    title: 'Hamon: Lumikha ng isang Bagong Showcase'
