---
hero_image: images/banner.png
title: Projeto Mostruário
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Nesse projeto, você irá criar um mostruário de seus projetos HTML e aprender sobre links e recursos embutidos.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Projeto Mostruário
  - 
    title: Adicionando Links para Páginas da Web
  - 
    title: 'Desafio: Adicionar outro link'
  - 
    title: Link para um trinket
  - 
    title: 'Desafio: Criar uma lista dos seus Projetos'
  - 
    title: Incorporando Projetos
  - 
    title: 'Desafio: Mais Projetos Incorporados'
  - 
    title: Crie um índice
  - 
    title: Voltando ao topo
  - 
    title: 'Desafio: Melhore seu Mostruário'
  - 
    title: 'Desafio: Crie um novo Mostruário'
