---
hero_image: images/banner.png
title: Projeto Mostruário
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crie um mostruário de seus projetos.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
- title: Introdução
- title: Adicionando Links para Páginas da Web
- title: 'Desafio: Adicione outro link'
- title: Link para um Trinket
  completion:
  - engaged
- title: 'Desafio: Crie uma lista dos seus Projetos'
- title: Incorporando Projetos
- title: 'Desafio: Incorpore Mais Projetos'
- title: Crie um índice
- title: Voltando ao topo
  completion:
  - internal
- title: 'Desafio: Melhore seu Mostruário'
- title: 'Desafio: Crie um novo Mostruário'
