---
hero_image: images / banner.png
title: Pameran Proyek
theme: pirus
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, desain-1, pemrograman-0, phys-comp-0, manufacture-0, community-0
description: Buat pajangan proyek web Anda.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: proyek
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: pengantar
  - 
    title: Menambahkan Tautan ke Halaman Web
  - 
    title: 'Tantangan: Tambahkan tautan lain'
  - 
    title: Tautkan ke Trinket
  - 
    title: 'Tantangan: Buat Daftar Proyek Anda'
  - 
    title: Menyematkan Proyek
  - 
    title: 'Tantangan: Tanamkan Lebih Banyak Proyek'
  - 
    title: Buat Daftar Isi
  - 
    title: Kembali ke Atas
  - 
    title: 'Tantangan: Tingkatkan Etalase Anda'
  - 
    title: 'Tantangan: Buat Pameran Baru'
