---
hero_image: images / banner.png
title: Projektbemutató
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Készítsen kirakatot webes projektjeiről.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: Linkek hozzáadása a weboldalakhoz
  - 
    title: 'Kihívás: Adj hozzá egy másik linket'
  - 
    title: Link egy talizmánhoz
  - 
    title: 'Kihívás: Készítsen projektek listáját'
  - 
    title: Projektek beágyazása
  - 
    title: 'Kihívás: Több projekt beágyazása'
  - 
    title: Hozzon létre egy tartalomjegyzéket
  - 
    title: Visszatérés a tetejére
  - 
    title: 'Kihívás: Javítani kell a kirakatot'
  - 
    title: 'Kihívás: hozzon létre egy új kirakatot'
