---
hero_image: images/banner.png
title: Projekti tutvustus
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Loo oma veebiprojektide tutvustus.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Sissejuhatus
  - 
    title: Linkide lisamine veebilehtedele
  - 
    title: 'Väljakutse: Lisa veel üks link'
  - 
    title: Link trinketile
  - 
    title: 'Väljakutse: Loo oma projektide nimekiri'
  - 
    title: Projektide manustamine
  - 
    title: 'Väljakutse: Manusta rohkem projekte'
  - 
    title: Loo sisukord
  - 
    title: Tagasi üles saamine
  - 
    title: 'Väljakutse: täiusta oma tutvustust'
  - 
    title: 'Väljakutse: Loo uus tutvustus'
