---
hero_image: images/banner.png
title: Moje projekty
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Stwórz listę swoich projektów.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Dodawanie linków do stron internetowych
  - 
    title: 'Wyzwanie: Dodaj kolejny link'
  - 
    title: Link do edytora Trinket
    completion:
      - engaged
  - 
    title: 'Wyzwanie: Stwórz listę swoich projektów'
  - 
    title: Osadzenie projektów
  - 
    title: 'Wyzwanie: Osadź więcej projektów'
  - 
    title: Stwórz spis treści
  - 
    title: Powrót do na górę
    completion:
      - internal
  - 
    title: 'Wyzwanie: udoskonal swoją prezentację'
  - 
    title: 'Wyzwanie: stwórz nową prezentację'
