---
hero_image: images/banner.png
title: Επίδειξη Έργων
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Δημιούργησε μία παρουσίαση των ιστοσελίδων σου.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Εισαγωγή
  - 
    title: Πρόσθεση συνδέσμων προς ιστοσελίδες
  - 
    title: 'Πρόκληση: Πρόσθεσε άλλο ένα σύνδεσμο'
  - 
    title: Σύνδεσμος προς ένα Trinket
    completion:
      - engaged
  - 
    title: 'Πρόκληση: Δημιούργησε μια λίστα των έργων σου'
  - 
    title: Ενσωμάτωση έργων
  - 
    title: 'Πρόκληση: Ενσωμάτωσε περισσότερα έργα'
  - 
    title: Δημιούργησε Πίνακα Περιεχομένων
  - 
    title: Επιστροφή στην κορυφή
    completion:
      - internal
  - 
    title: 'Πρόκληση: Βελτίωσε την παρουσίασή σου'
  - 
    title: 'Πρόκληση: Δημιούργησε μια νέα Παρουσίαση'
