hero_image: images/banner.png
title: Portfolio
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
description: Créer une vitrine virtuelle de vos projets web.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introduction
- title: Ajouter des liens à ta page
- title: 'Défi: Ajouter un autre lien'
- title: Lien vers un trinket
- title: 'Défi: Créer une liste de tes projets'
- title: Embarque encore plus de projets
- title: 'Défi: Embarque encore plus de projets'
- title: Crée un sommaire
- title: Revenir en haut
- title: 'Défi: Améliore ton portfolio'
- title: 'Défi: Crée un nouveau showcase'

