---
hero_image: images/banner.png
title: Portfolio
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Créer un portfolio de tes projets web.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ajout de liens vers des pages Web
  - 
    title: 'Défi : ajouter un autre lien'
  - 
    title: Lien vers un Trinket
    completion:
      - engaged
  - 
    title: 'Défi : créer une liste de tes projets'
  - 
    title: Intégration de projets
  - 
    title: 'Défi : intégrer plus de projets'
  - 
    title: Créer une table des matières
  - 
    title: Revenir en haut
    completion:
      - internal
  - 
    title: 'Défi : améliorer ton portfolio'
  - 
    title: 'Défi : créer un nouveau portfolio'
