---
hero_image: images/banner.png
title: Proje Vitrini
theme: turkuaz
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-1, programlama-0, fiziksel-hesaplama-0, üretim-0, topluluk-0
description: Web projelerinizin için bir vitrin oluşturun.
original_url: https://codeclubprojects.org/en-GB/webdev/project-showcase
interests: ''
technologies: html-css-javascript
site_areas: projeler
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017/01/01
steps:
  - 
    title: Giriş
  - 
    title: Web Sayfalarına Bağlantı Ekleme
  - 
    title: 'Meydan okuma: Başka bir bağlantı ekle'
  - 
    title: Trinklet’e bağlantı oluştur
  - 
    title: 'Meydan okuma: Projelerinizin bir listesini oluşturun'
  - 
    title: Yerleşik Projeler
  - 
    title: 'Meydan okuma: Daha Fazla Proje Yerleştir'
  - 
    title: İçerikler Tablosu Oluştur
  - 
    title: Başa Dön
  - 
    title: 'Meydan Okuma: Vitrininizi Geliştirin'
  - 
    title: 'Meydan Okuma: Yeni Bir Vitrin Oluştur'
